language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer --dev install

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm
